### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by pjmolina** [jasonwyatt/docker-nginx-loadbalancer#2]
Great work!
It this working with docker-compose?

Testing it I must be doing something wrong. I tried:

```
docker run --name lb2 -d -P --link app1:app1 --link app2:app2 --link app3:app3 jasonwyatt/nginx-loadbalancer
```

With app1, app2 and app3 running exposing port 80.

But get the following error:

```
>docker logs lb2
No fig prefix found.
Starting Nginx...
```

and no load-balancing working. Connection refused on port 80 on lb2.

**Comment by jasonwyatt** [comment]
Great question, I haven't tried working with composer yet.  If you figure out a fix, let me know! (or better: make a pull request)

**Comment by pjmolina** [comment]
Hi Jason I resolved the problems on my case of use:
1. App instances must be named following the convention `app_<n>` instead of `app<n>`.
2. The environmental option `<serviceName>_PATH = "/"` must be passed to the load balancer on creation.

So a sample usage would be:

```
docker run --name app_1 -d pjmolina/appimage
docker run --name app_2 -d pjmolina/appimage
docker run --name lb -d -p "80:80" --link app_1:app_1 --link app_2:app_2 \
           -e "APP_PATH=/" jasonwyatt/nginx-loadbalancer
```

On the second issue **docker-compose**, I was successful to launch `docker-composer up -d` using the following **docker-composer.yml** file:

```
db:
  image: dockerfile/mongodb
  ports:
  - "27017"

app:
  build: .
  environment:
    PORT: 80
    SERVICE_NAME: app
  ports:
  - "80"
  links:
  - "db:DB"

lb:
  image: jasonwyatt/nginx-loadbalancer
  environment:
     APP_PATH: "/"
  links:
  - app
  ports:
  - "80:80"
```

The only issue to raise as a future enhancement is to dynamically add or remove app instances when using the scale command: `docker-compose scale app=3`
